version: 0.0
os: linux
files:
  - source: /
    destination: /var/www/Virtual-Map-Walker
permissions:
  - object: /var/www/
    owner: ec2-user
    mode: 775
hooks:
  ApplicationStop:
    - location: scripts/stop_server.sh
      timeout: 100

  BeforeInstall:
    - location: scripts/clean.sh
      timeout: 200

  AfterInstall:
    - location: scripts/bundle_install.sh
      timeout: 300

  ApplicationStart:
    - location: scripts/start_server.sh
      timeout: 200
